### ISSUE TITLE
[task] how to manipulate website using dom

### ISSUE THREAD

**Issue by themetronome** [Atlantis-Academy/frontend-study-themetronome#10]
**Основы JavaScript**

> Практика. Действия со страницей

- Удалить все рекламные блоки со страницы (правая часть сайта)

- Изменить жанр фильма, поменять _комедия_ на _драма_

- Изменить задний фон на изображение **bg.jpg** (в папке img). Реализация только средствами JavaScript

- Список фильмов на странице сформировать на основании данных из этого JS файла. Отсортировать их по алфавиту

- Добавить нумерацию выведенных фильмов

**Comment by TorinAsakura** [comment]
сайдбар
