### ISSUE TITLE
[task] mastering modal windows

### ISSUE THREAD

**Issue by themetronome** [Atlantis-Academy/frontend-study-themetronome#20]
**JavaScript в работе**

> Создаем модальное окно

- разобраться с реализацией [вёрстки](https://github.com/Atlantis-Academy/frontend-study-themetronome/blob/master/practice/healthy-food-delivery/public/index.html) страницы и выделить элементы, которые должны триггерить вызов модального окна
- реализовать вывод модального окна при клике(сделать visible)

**Comment by TorinAsakura** [comment]
> **JavaScript в работе**
> 
> > Создаем модальное окно
> 
> * изучить существующую вёрстку проекта
> * выделить элементы которые должны триггерить вызов модального окна
> * реализовать вывод модального окна при клике(сделать visible)

Указатель без контекста, какая к хренам существующая вёрстка?

**Comment by themetronome** [comment]
> > **JavaScript в работе**
> > > Создаем модальное окно
> > 
> > 
> > 
> > * изучить существующую вёрстку проекта
> > * выделить элементы которые должны триггерить вызов модального окна
> > * реализовать вывод модального окна при клике(сделать visible)
> 
> Указатель без контекста, какая к хренам существующая вёрстка?

В кейсе где мне нужно реализовать некую логику, уже на свёрстанной странице, например. Как было бы верно обозначить задачу?

**Comment by TorinAsakura** [comment]
> > > **JavaScript в работе**
> > > > Создаем модальное окно
> > > 
> > > 
> > > 
> > > * изучить существующую вёрстку проекта
> > > * выделить элементы которые должны триггерить вызов модального окна
> > > * реализовать вывод модального окна при клике(сделать visible)
> > 
> > 
> > Указатель без контекста, какая к хренам существующая вёрстка?
> 
> В кейсе где мне нужно реализовать некую логику, уже на свёрстанной странице, например. Как было бы верно обозначить задачу?

Указать ссылки на фрагменты/модули/компоненты, иначе выглядит так: "мне нужно купить гитару в музыкальном магазине" ни **где**, ни **когда**
