### ISSUE TITLE
[task] packages configuration for using typescript

### ISSUE THREAD

**Issue by themetronome** [Atlantis-Academy/frontend-study-themetronome#24]
- добавить tsconfig.json файл в корень и в директорию каждого пакета
- рассмотреть [примеры конфигов](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)
- указать параметры `compilerOptions` либо как в примере документации, либо, надеюсь, @TorinAsakura подскажет необходимые параметры (возможно будет целесообразнее подсмотреть пример конфигурации [здесь](https://github.com/Atlantis-Lab/serenity))

**Comment by TorinAsakura** [comment]
> * добавить tsconfig.json файл в корень и в директорию каждого пакета
> * рассмотреть [примеры конфигов](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)
> * указать параметры `compilerOptions` либо как в примере документации, либо, надеюсь, @TorinAsakura подскажет необходимые параметры (возможно будет целесообразнее подсмотреть пример конфигурации [здесь](https://github.com/Atlantis-Lab/serenity))

https://github.com/Atlantis-Lab/config - сделал репу публичной, читайте
