### ISSUE TITLE
[task] prompt-questions automating using loops and validate it using conditions 

### ISSUE THREAD

**Issue by themetronome** [Atlantis-Academy/frontend-study-themetronome#3]
**Основы JavaScript**

> Практика, ч2. Применяем условия и циклы

- Автоматизировать вопросы пользователю про фильмы при помощи цикла
- Сделать так, чтобы пользователь не мог оставить ответ в виде пустой строки, отменить, или ввести название фильма длинее, чем 50 символов. Если это происходит - возвращаем пользователя к ответу на вопрос с пустой строкой
- При помощи условий проверить поле `personalMovieDB.count`, и если он меньше 10 - вывести сообщение о слишком маленьком количестве просмотренных фильмов, если 10-30 - "Классический зритель", а если более 30 - "Киноман". Ошибка - если не один из вышеозвученных вариантов не подошёл

p.s. кодовая база берётся из прошлой практики

**Comment by themetronome** [comment]
Продвигаясь по задачам пунктам практики, я понял что подзадачи имеют разную природу коммитов(исходя из [конвенции](https://www.conventionalcommits.org/ru/v1.0.0-beta.4/)), а именно: в первой подзадаче, мы используем две функции `prompt` в цикле, вместо 4 записей результата `prompt` в переменные. Это больше похоже на рефакторинг, новых фич нет, только более элегантное решение, нежели чем то, что мы использовали в первой практике. Остальные две подзадачи это фичи - здесь всё понятно. Мой вопрос в том, как красиво оформить ПР, т.к. получается ветки должно быть две, а тип у них разный

**Comment by TorinAsakura** [comment]
> Продвигаясь по задачам пунктам практики, я понял что подзадачи имеют разную природу коммитов(исходя из [конвенции](https://www.conventionalcommits.org/ru/v1.0.0-beta.4/)), а именно: в первой подзадаче, мы используем две функции `prompt` в цикле, вместо 4 записей результата `prompt` в переменные. Это больше похоже на рефакторинг, новых фич нет, только более элегантное решение, нежели чем то, что мы использовали в первой практике. Остальные две подзадачи это фичи - здесь всё понятно. Мой вопрос в том, как красиво оформить ПР, т.к. получается ветки должно быть две, а тип у них разный

верно, но, ветка должна создаваться в контексте задачи, а не в контексте вкладов, а вот вкладов (коммитов) может быть два и да они могут быть с разным типом

**Comment by TorinAsakura** [comment]
@themetronome пожалуйста, не забывай заполнять issue fields -> sidebar
