### ISSUE TITLE
[chore] eslint testing at merging pull request using github actions

### ISSUE THREAD

**Issue by themetronome** [Atlantis-Academy/frontend-study-themetronome#31]
### Какого рода задача?
реализовать проверку кода линтером при мердже пулл реквеста используя github actions

### Что и где будем менять?

- [x] добавить в директорию .github конфигурацию для проверок(check.yml), который и будет говорить гитхабу какого рода проводить проверки при мердже в рабочую ветку
- [x] убедиться в том, что экшены цепляют скрипт из package.json и отрабатывают

### Укажите референс
- https://github.com/Atlantis-Academy/frontend-study-themetronome/issues/23 - здесь реализованы конфигурации проверок линтера
- https://github.com/Atlantis-Lab/reactjs/blob/master/.github/workflows/check.yml - а это пример уже готовой реализации тестов

**Comment by TorinAsakura** [comment]
@themetronome @easymon3y5niper что за портянка? Где таски?
